openvswitch: Update to support dpdk 17 to fix build failure
Issue: LIN10-2824

do_configure failure:
| checking for /build/tmp-glibc/work/corei7-64-wrs-linux/openvswitch/2.7.1+b29cb89e9e9fe3119b2e5dd5d4fb79141635b7cc-r0/recipe-sysroot/opt/dpdk/share/x86_64-native-linuxapp-gcc/include/rte_config.h... configure: error: cannot check for file existence when cross compiling
| NOTE: The following config.log files may provide further information.
| NOTE: /build/tmp-glibc/work/corei7-64-wrs-linux/openvswitch/2.7.1+b29cb89e9e9fe3119b2e5dd5d4fb79141635b7cc-r0/build/config.log
| ERROR: configure failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /build/tmp-glibc/work/corei7-64-wrs-linux/openvswitch/2.7.1+b29cb89e9e9fe3119b2e5dd5d4fb79141635b7cc-r0/temp/log.do_configure.50393)

do_compile failure:
| ../git/lib/netdev-dpdk.c:34:10: fatal error: rte_virtio_net.h: No such file or directory
|  #include <rte_virtio_net.h>
|           ^~~~~~~~~~~~~~~~~~
| compilation terminated.

Signed-off-by: He Zhe <zhe.he@windriver.com>